---auto-finder.sections — backwards-compat facade (ADR 0026 Phase 2).
---
---The view registry moved to `auto-finder.views` in Phase 2.
---External consumers (third-party plugins doing
---`require("auto-finder.sections")` to enumerate views, or older
---versions of internal code paths that haven't been updated yet)
---resolve through this one-line re-export.
---
---**This facade is scheduled for removal at the next minor bump.**
---When v0.3.0 lands, callers should switch to
---`require("auto-finder.views")`.
---
---@module 'auto-finder.sections'
return require("auto-finder.views")
